### ISSUE TITLE
Inetgration of Gigahorse Plots 

### ISSUE THREAD

**Issue by Exzellenz** [foxypool/foxy-farmer#8] opened 2023-10-01 09:22 UTC
Hi this is more of a feature request. Would it be possible to add Support for gigahorse Compressed Plots to the Farmer ? Or is this planned in the ner future ? 
Iam one of the user who where at Flexpool before and  have 2 PB of Gigahorse plots. 
running  a fullnude is no Option because of Traffic restrictions. 
I guess you could get  a lot of the Flexpool Userbase by adding support for Gigahorse Plots.

**Comment by felixbrucker** [comment] 2023-10-01 12:38
Unfortunately integration into foxy-farmer won't be possible because gigahorse is closed source and foxy-farmer directly integrates with the chia-blockchain source code, but a gigahorse farming gateway is planned, so you won't need to run a gigahorse full node, just your farmer and harvesters.

**Comment by Exzellenz** [comment] 2023-10-06 14:20
yes sure thats fair enough i look forward to it. Thank you

**Comment by felixbrucker** [comment] 2023-10-06 14:45
Update: A gigahorse foxy-farmer (foxy-gh-farmer) is available for testing here: https://github.com/foxypool/foxy-gh-farmer
Its basically a wrapper around the manual tasks of setting up a gigahorse farmer & harvester with the foxy hosted gigahorse node

Its currently still in testing, so if you want to help out try it, a binary is available in the latest action run(s) but it can also be run from source. I plan to make an official release (and add docs etc for it) in the coming days when everything is tested and confirmed working 👍 

Things i have not tested yet:
- arm support

**Comment by Exzellenz** [comment] 2023-10-07 14:24
Thank you i will look into this once i have some Time to play arround  Running from source should not be a problem.

**Comment by felixbrucker** [comment] 2023-10-08 10:38
Foxy-GH-Farmer is now officially released btw 👍

**Comment by felixbrucker** [comment] 2023-10-13 04:06
Closing here

**Closed as completed by felixbrucker** 2023-10-13 04:06 UTC
